### ISSUE TITLE
HTTPS Support?

### ISSUE THREAD

**Issue by CammmPW** [Relfos/LunarServer#1]
Hi!

I use your server on a project of mine and I find it much easier and more efficient than WatsonWebserver. However, the thing I miss from Watson was SSL capabilities. Is this something you could potentially add?

Kind Regards,
Cam.

**Comment by Relfos** [comment]
Hello, I did not add SSL capability because looked to be something quite complex to implement.

If the reason you need this is to host HTTPS sites, it is still possible, eg: https://lunarlabs.pt/ is running on LunarServer, but it requires a trick.

How I do it is by instead of exposing LunarServer directly to the outside world, I instead use Nginx server as a reverse proxy server, so basically it goes like this
outside world > Nginx (HTTPS) > Lunarserver (HTTP)

I use Certbot to generate the HTTPS certificates. And this kind of reverse proxy setup can be done with other servers like Apache etc. I do recommend this approach because it is more safe to have those big projects handling the HTTPS part, as it is a sensitive subject that if implemented wrong could expose a website to security risks

**Comment by CammmPW** [comment]
Oh, interesting! I never thought about that workaround. That should work perfectly fine. Thank you for your very very swift response!
